
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point rx_i rx_i -type PI PI
add mapped point rx_read_en rx_read_en -type PI PI
add mapped point tx_wr_en tx_wr_en -type PI PI
add mapped point tx_din[7] tx_din[7] -type PI PI
add mapped point tx_din[6] tx_din[6] -type PI PI
add mapped point tx_din[5] tx_din[5] -type PI PI
add mapped point tx_din[4] tx_din[4] -type PI PI
add mapped point tx_din[3] tx_din[3] -type PI PI
add mapped point tx_din[2] tx_din[2] -type PI PI
add mapped point tx_din[1] tx_din[1] -type PI PI
add mapped point tx_din[0] tx_din[0] -type PI PI

//output ports
add mapped point tx_o tx_o -type PO PO
add mapped point rx_dout[7] rx_dout[7] -type PO PO
add mapped point rx_dout[6] rx_dout[6] -type PO PO
add mapped point rx_dout[5] rx_dout[5] -type PO PO
add mapped point rx_dout[4] rx_dout[4] -type PO PO
add mapped point rx_dout[3] rx_dout[3] -type PO PO
add mapped point rx_dout[2] rx_dout[2] -type PO PO
add mapped point rx_dout[1] rx_dout[1] -type PO PO
add mapped point rx_dout[0] rx_dout[0] -type PO PO
add mapped point rx_fifo_full rx_fifo_full -type PO PO
add mapped point rx_fifo_empty rx_fifo_empty -type PO PO
add mapped point tx_fifo_full tx_fifo_full -type PO PO

//inout ports




//Sequential Pins
add mapped point rx_inst/bau_gen_inst/baudcount_reg[6]/q rx_inst/bau_gen_inst/baudcount_reg_reg[6]/Q -type DFF DFF
add mapped point rx_inst/bau_gen_inst/baudcount_reg[5]/q rx_inst/bau_gen_inst/baudcount_reg_reg[5]/Q -type DFF DFF
add mapped point rx_inst/bau_gen_inst/baudcount_reg[4]/q rx_inst/bau_gen_inst/baudcount_reg_reg[4]/Q -type DFF DFF
add mapped point rx_inst/bau_gen_inst/baudcount_reg[3]/q rx_inst/bau_gen_inst/baudcount_reg_reg[3]/Q -type DFF DFF
add mapped point rx_inst/bau_gen_inst/baudcount_reg[2]/q rx_inst/bau_gen_inst/baudcount_reg_reg[2]/Q -type DFF DFF
add mapped point rx_inst/bau_gen_inst/baudcount_reg[1]/q rx_inst/bau_gen_inst/baudcount_reg_reg[1]/Q -type DFF DFF
add mapped point rx_inst/bau_gen_inst/baudcount_reg[0]/q rx_inst/bau_gen_inst/baudcount_reg_reg[0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[0]/q rx_inst/fifo_inst/memory_inst/dout_reg[0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[1]/q rx_inst/fifo_inst/memory_inst/dout_reg[1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[2]/q rx_inst/fifo_inst/memory_inst/dout_reg[2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[3]/q rx_inst/fifo_inst/memory_inst/dout_reg[3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[4]/q rx_inst/fifo_inst/memory_inst/dout_reg[4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[5]/q rx_inst/fifo_inst/memory_inst/dout_reg[5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[6]/q rx_inst/fifo_inst/memory_inst/dout_reg[6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/dout[7]/q rx_inst/fifo_inst/memory_inst/dout_reg[7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[0][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[0][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[1][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[1][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[2][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[2][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[3][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[3][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[4][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[4][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[5][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[5][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[6][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[6][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[7][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[7][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[8][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[8][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[9][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[9][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[10][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[10][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[11][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[11][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[12][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[12][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[13][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[13][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[14][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[14][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][0]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][1]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][2]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][3]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][4]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][4]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][5]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][5]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][6]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][6]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/memory_inst/mem[15][7]/q rx_inst/fifo_inst/memory_inst/mem_reg[15][7]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/read_pointer_inst/rd_ptr[3]/q rx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/read_pointer_inst/rd_ptr[2]/q rx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/read_pointer_inst/rd_ptr[1]/q rx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/read_pointer_inst/rd_ptr[0]/q rx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[0]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/state_inst/f_empty/q rx_inst/fifo_inst/state_inst/f_empty_reg/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/state_inst/f_full/q rx_inst/fifo_inst/state_inst/f_full_reg/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/write_pointer_inst/wr_ptr[3]/q rx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[3]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/write_pointer_inst/wr_ptr[2]/q rx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[2]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/write_pointer_inst/wr_ptr[1]/q rx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[1]/Q -type DFF DFF
add mapped point rx_inst/fifo_inst/write_pointer_inst/wr_ptr[0]/q rx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[0]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[4]/q rx_inst/uart_rx_inst/dout_o_reg[4]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[6]/q rx_inst/uart_rx_inst/dout_o_reg[6]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[7]/q rx_inst/uart_rx_inst/dout_o_reg[7]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[0]/q rx_inst/uart_rx_inst/dout_o_reg[0]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[2]/q rx_inst/uart_rx_inst/dout_o_reg[2]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[5]/q rx_inst/uart_rx_inst/dout_o_reg[5]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[3]/q rx_inst/uart_rx_inst/dout_o_reg[3]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/dout_o[1]/q rx_inst/uart_rx_inst/dout_o_reg[1]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/rx_done_o/q rx_inst/uart_rx_inst/rx_done_o_reg/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/rx/q rx_inst/uart_rx_inst/rx_reg/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/meta/q rx_inst/uart_rx_inst/meta_reg/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/ncount[1]/q rx_inst/uart_rx_inst/ncount_reg[1]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/ncount[0]/q rx_inst/uart_rx_inst/ncount_reg[0]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/state[0]/q rx_inst/uart_rx_inst/state_reg[0]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/ncount[2]/q rx_inst/uart_rx_inst/ncount_reg[2]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/scount[1]/q rx_inst/uart_rx_inst/scount_reg[1]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/scount[3]/q rx_inst/uart_rx_inst/scount_reg[3]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[1]/q rx_inst/uart_rx_inst/data_reg_reg[1]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/scount[2]/q rx_inst/uart_rx_inst/scount_reg[2]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[0]/q rx_inst/uart_rx_inst/data_reg_reg[0]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[4]/q rx_inst/uart_rx_inst/data_reg_reg[4]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[2]/q rx_inst/uart_rx_inst/data_reg_reg[2]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[3]/q rx_inst/uart_rx_inst/data_reg_reg[3]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[7]/q rx_inst/uart_rx_inst/data_reg_reg[7]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[5]/q rx_inst/uart_rx_inst/data_reg_reg[5]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/data_reg[6]/q rx_inst/uart_rx_inst/data_reg_reg[6]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/scount[0]/q rx_inst/uart_rx_inst/scount_reg[0]/Q -type DFF DFF
add mapped point rx_inst/uart_rx_inst/state[1]/q rx_inst/uart_rx_inst/state_reg[1]/Q -type DFF DFF
add mapped point rx_inst/fifo_wr_en/q rx_inst/fifo_wr_en_reg/Q -type DFF DFF
add mapped point tx_inst/bau_gen_inst/baudcount_reg[6]/q tx_inst/bau_gen_inst/baudcount_reg_reg[6]/Q -type DFF DFF
add mapped point tx_inst/bau_gen_inst/baudcount_reg[5]/q tx_inst/bau_gen_inst/baudcount_reg_reg[5]/Q -type DFF DFF
add mapped point tx_inst/bau_gen_inst/baudcount_reg[4]/q tx_inst/bau_gen_inst/baudcount_reg_reg[4]/Q -type DFF DFF
add mapped point tx_inst/bau_gen_inst/baudcount_reg[3]/q tx_inst/bau_gen_inst/baudcount_reg_reg[3]/Q -type DFF DFF
add mapped point tx_inst/bau_gen_inst/baudcount_reg[2]/q tx_inst/bau_gen_inst/baudcount_reg_reg[2]/Q -type DFF DFF
add mapped point tx_inst/bau_gen_inst/baudcount_reg[1]/q tx_inst/bau_gen_inst/baudcount_reg_reg[1]/Q -type DFF DFF
add mapped point tx_inst/bau_gen_inst/baudcount_reg[0]/q tx_inst/bau_gen_inst/baudcount_reg_reg[0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[0]/q tx_inst/fifo_inst/memory_inst/dout_reg[0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[1]/q tx_inst/fifo_inst/memory_inst/dout_reg[1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[2]/q tx_inst/fifo_inst/memory_inst/dout_reg[2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[3]/q tx_inst/fifo_inst/memory_inst/dout_reg[3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[4]/q tx_inst/fifo_inst/memory_inst/dout_reg[4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[5]/q tx_inst/fifo_inst/memory_inst/dout_reg[5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[6]/q tx_inst/fifo_inst/memory_inst/dout_reg[6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/dout[7]/q tx_inst/fifo_inst/memory_inst/dout_reg[7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[0][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[0][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[1][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[1][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[2][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[2][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[3][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[3][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[4][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[4][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[5][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[5][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[6][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[6][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[7][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[7][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[8][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[8][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[9][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[9][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[10][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[10][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[11][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[11][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[12][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[12][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[13][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[13][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[14][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[14][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][0]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][1]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][2]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][3]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][4]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][4]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][5]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][5]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][6]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][6]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/memory_inst/mem[15][7]/q tx_inst/fifo_inst/memory_inst/mem_reg[15][7]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/read_pointer_inst/rd_ptr[3]/q tx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/read_pointer_inst/rd_ptr[2]/q tx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/read_pointer_inst/rd_ptr[1]/q tx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/read_pointer_inst/rd_ptr[0]/q tx_inst/fifo_inst/read_pointer_inst/rd_ptr_reg[0]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/state_inst/f_empty/q tx_inst/fifo_inst/state_inst/f_empty_reg/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/state_inst/f_full/q tx_inst/fifo_inst/state_inst/f_full_reg/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/write_pointer_inst/wr_ptr[3]/q tx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[3]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/write_pointer_inst/wr_ptr[2]/q tx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[2]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/write_pointer_inst/wr_ptr[1]/q tx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[1]/Q -type DFF DFF
add mapped point tx_inst/fifo_inst/write_pointer_inst/wr_ptr[0]/q tx_inst/fifo_inst/write_pointer_inst/wr_ptr_reg[0]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/tx_done_o/q tx_inst/uart_tx_inst/tx_done_o_reg/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/ncount[1]/q tx_inst/uart_tx_inst/ncount_reg[1]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/state[0]/q tx_inst/uart_tx_inst/state_reg[0]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[6]/q tx_inst/uart_tx_inst/data_reg_reg[6]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[5]/q tx_inst/uart_tx_inst/data_reg_reg[5]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[4]/q tx_inst/uart_tx_inst/data_reg_reg[4]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[1]/q tx_inst/uart_tx_inst/data_reg_reg[1]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/tx_o_buf/q tx_inst/uart_tx_inst/tx_o_buf_reg/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[2]/q tx_inst/uart_tx_inst/data_reg_reg[2]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[3]/q tx_inst/uart_tx_inst/data_reg_reg[3]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[0]/q tx_inst/uart_tx_inst/data_reg_reg[0]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/ncount[2]/q tx_inst/uart_tx_inst/ncount_reg[2]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/ncount[0]/q tx_inst/uart_tx_inst/ncount_reg[0]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/data_reg[7]/q tx_inst/uart_tx_inst/data_reg_reg[7]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/scount[1]/q tx_inst/uart_tx_inst/scount_reg[1]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/scount[2]/q tx_inst/uart_tx_inst/scount_reg[2]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/scount[3]/q tx_inst/uart_tx_inst/scount_reg[3]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/scount[0]/q tx_inst/uart_tx_inst/scount_reg[0]/Q -type DFF DFF
add mapped point tx_inst/uart_tx_inst/state[1]/q tx_inst/uart_tx_inst/state_reg[1]/Q -type DFF DFF
add mapped point tx_inst/start_tx_delayed/q tx_inst/start_tx_delayed_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
